- name: Create Ec2 instance
  connection: local
  hosts: localhost
  become: yes
  vars:
    subnet_id: subnet-042e14877f4764239
    sg_id: sg-00c5900657b037b30
    instance_type: t3.micro
    image_id: ami-09c813fb71547fc4f
    # region: us-east-1
  instance:
    - mysql
    - backend
    - frontend

  tasks:
  - name: install AWS python libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create Ec2 instances and route53 
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      # region: "{{ region }}"
      image_id: "{{ image_id }}"
      instance_type: "{{ instance_type }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      wait: yes  # Optional: waits for the instance to be in the running state
    loop: "{{ instance }}"
    register: ec2_info
    
  - name: print ec2_info output
    ansible.builtin.debug:
      msg: "output: {{ ec2_info }}"